# Generated by Django 5.1.4 on 2026-08-06 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='project',
            new_name='projects_pr_status_b6b628_idx',
            old_name='projects_pr_status_7c0a8f_idx',
        ),
        migrations.RenameIndex(
            model_name='projectfile',
            new_name='projects_pr_project_227d05_idx',
            old_name='projects_pr_project_6b4f2a_idx',
        ),
        migrations.RenameIndex(
            model_name='projectfile',
            new_name='projects_pr_project_4c36bc_idx',
            old_name='projects_pr_project_9e1d3c_idx',
        ),
    ]
