# Generated by Django 5.1.4 on 2026-08-06 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_graphsnapshot'),
        ('projects', '0002_rename_projects_pr_status_7c0a8f_idx_projects_pr_status_b6b628_idx_and_more'),
    ]

    operations = [
    ]
